Imported pandas Library

In [17]:
import pandas as pd

Loaded the Netflix Dataset

In [18]:
df=pd.read_csv('NetFlix.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

Checked columns in dataset

In [19]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genres', 'description'],
      dtype='object')

Performed Statistical analysis

In [20]:
df.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

Mean

In [21]:
df.mean(numeric_only=True)

release_year    2013.932580
duration          69.122769
dtype: float64

Median

In [22]:
df.median(numeric_only=True)

release_year    2017.0
duration          88.0
dtype: float64

Mode

In [23]:
df.mode()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,Movie,#Alive,"Raúl Campos, Jan Suter",David Attenborough,United States,1-Jan-20,2018.0,TV-MA,1.0,Documentaries,A surly septuagenarian gets another chance at ...
1,s10,NaN,#AnneFrank - Parallel Stories,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Multiple women report their husbands as missin...
2,s100,NaN,#FriendButMarried,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s1000,NaN,#FriendButMarried 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s1001,NaN,#Roxy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s995,NaN,忍者ハットリくん,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7783,s996,NaN,海的儿子,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7784,s997,NaN,마녀사냥,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7785,s998,NaN,반드시 잡는다,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7786,s999,NaN,최강전사 미니특공대 : 영웅의 탄생,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Standard Deviation

In [24]:
df.std(numeric_only=True)

release_year     8.757395
duration        50.950743
dtype: float64

Variance

In [25]:
df.var(numeric_only=True)

release_year      76.691961
duration        2595.978247
dtype: float64